twilio: # SMS OTP config
  account-sid: ACa71f57f85ce6d75ec2ed23f2ac448d9a
  auth-token: 35695545554a2c9ee0b09f7d86c02425
  from-number: +15513487478   # Twilio number

spring:
  kafka:
    bootstrap-servers: localhost:9092
    group-id: notification-service
    
eureka:
  instance:
    preferIpAddress: true
  server:
    fetch-registry: true
    register-with-eureka: true
  client:
      service-url:
          defaultZone: "http://localhost:8761/eureka/"
